name: ci

# Define quando a ação será executada. Neste caso, em cada 'push'.
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'  # Substitua pelo a versão do Python que você usa
    - name: Instalar GeckoDriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
        tar -xzf geckodriver-v0.29.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/    
    - name: Instalar dependências
      run: |
        pip install -r requirements.txt
    - name: Rodar testes 
      run: pytest tests